import { Recipe } from '../types';

// v1.2 — 6 Pakistani household recipes shipped as starter content.
// Users can edit/delete these. They're only written to storage on first launch
// when `hm_recipes` has no existing entries (handled by useStorage default).

const NOW = new Date().toISOString();

export const SEED_RECIPES: Recipe[] = [
  {
    id: 1,
    name: 'Chicken Biryani',
    servings: 4,
    prepMinutes: 30,
    cookMinutes: 60,
    ingredients: [
      { name: 'Basmati Rice', qty: 500, unit: 'g' },
      { name: 'Chicken', qty: 1, unit: 'kg' },
      { name: 'Yogurt', qty: 250, unit: 'g' },
      { name: 'Onions', qty: 3, unit: 'pcs' },
      { name: 'Tomatoes', qty: 2, unit: 'pcs' },
      { name: 'Ginger-Garlic Paste', qty: 2, unit: 'tbsp' },
      { name: 'Biryani Masala', qty: 1, unit: 'packet' },
      { name: 'Green Chillies', qty: 4, unit: 'pcs' },
      { name: 'Mint Leaves', qty: 1, unit: 'bunch' },
      { name: 'Oil', qty: 150, unit: 'ml' },
      { name: 'Salt', qty: 2, unit: 'tsp' },
    ],
    steps: [
      'Soak basmati rice in water for 30 minutes.',
      'Fry sliced onions until golden brown and set aside.',
      'Cook chicken with yogurt, ginger-garlic paste, tomatoes, and biryani masala until tender.',
      'Parboil the soaked rice with whole spices and salt, then drain.',
      'Layer the rice and chicken in a heavy-bottom pot. Top with fried onions, mint, and chillies.',
      'Cover tightly and steam on low heat for 20 minutes (dum).',
      'Fluff gently with a fork and serve with raita.',
    ],
    notes: 'Use long-grain basmati for the best texture. Dum cooking is the secret to separated grains.',
    createdAt: NOW,
  },
  {
    id: 2,
    name: 'Daal Chawal',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    ingredients: [
      { name: 'Masoor Daal', qty: 250, unit: 'g' },
      { name: 'Rice', qty: 400, unit: 'g' },
      { name: 'Onions', qty: 1, unit: 'pcs' },
      { name: 'Tomatoes', qty: 1, unit: 'pcs' },
      { name: 'Garlic', qty: 4, unit: 'cloves' },
      { name: 'Cumin Seeds', qty: 1, unit: 'tsp' },
      { name: 'Turmeric', qty: 1, unit: 'tsp' },
      { name: 'Red Chilli Powder', qty: 1, unit: 'tsp' },
      { name: 'Oil', qty: 50, unit: 'ml' },
      { name: 'Salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Rinse daal and boil with turmeric, chilli powder, and salt until soft.',
      'Heat oil in a pan, add cumin and chopped onions, fry until golden.',
      'Add garlic and tomatoes; cook until oil separates.',
      'Pour the tarka (tempering) over cooked daal and stir.',
      'Cook rice separately — boil with a pinch of salt until tender.',
      'Serve daal hot over rice with a squeeze of lemon.',
    ],
    notes: 'Comfort food at its finest. Serve with pickle and a slice of onion.',
    createdAt: NOW,
  },
  {
    id: 3,
    name: 'Chicken Karahi',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 40,
    ingredients: [
      { name: 'Chicken', qty: 1, unit: 'kg' },
      { name: 'Tomatoes', qty: 4, unit: 'pcs' },
      { name: 'Ginger-Garlic Paste', qty: 2, unit: 'tbsp' },
      { name: 'Green Chillies', qty: 4, unit: 'pcs' },
      { name: 'Ginger', qty: 1, unit: 'inch' },
      { name: 'Coriander', qty: 1, unit: 'bunch' },
      { name: 'Black Pepper', qty: 1, unit: 'tsp' },
      { name: 'Red Chilli', qty: 1, unit: 'tsp' },
      { name: 'Oil', qty: 100, unit: 'ml' },
      { name: 'Salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a karahi; add ginger-garlic paste and chicken, fry until browned.',
      'Add chopped tomatoes and salt, cook covered until tomatoes break down.',
      'Uncover and stir-fry on high heat until oil separates.',
      'Add black pepper, red chilli, and slit green chillies.',
      'Garnish with julienned ginger and chopped coriander.',
      'Serve hot with naan or roti.',
    ],
    notes: 'Dhaba-style karahi uses high heat. Don\'t overcrowd the pan.',
    createdAt: NOW,
  },
  {
    id: 4,
    name: 'Chicken Pulao',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 45,
    ingredients: [
      { name: 'Basmati Rice', qty: 500, unit: 'g' },
      { name: 'Chicken', qty: 750, unit: 'g' },
      { name: 'Onions', qty: 2, unit: 'pcs' },
      { name: 'Ginger-Garlic Paste', qty: 2, unit: 'tbsp' },
      { name: 'Cumin Seeds', qty: 1, unit: 'tsp' },
      { name: 'Bay Leaves', qty: 2, unit: 'pcs' },
      { name: 'Cinnamon Stick', qty: 1, unit: 'pcs' },
      { name: 'Cardamom', qty: 4, unit: 'pcs' },
      { name: 'Oil', qty: 100, unit: 'ml' },
      { name: 'Salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Soak basmati rice for 20 minutes.',
      'Fry onions in oil until translucent, add whole spices.',
      'Add chicken and ginger-garlic paste, cook until chicken is browned.',
      'Pour in water (2x rice volume) and bring to a boil.',
      'Add drained rice and salt, cover and cook on low until water is absorbed.',
      'Rest 10 minutes off heat before serving.',
    ],
    notes: 'Use the rice-to-water ratio of 1:2 for fluffy pulao.',
    createdAt: NOW,
  },
  {
    id: 5,
    name: 'Kheer',
    servings: 6,
    prepMinutes: 5,
    cookMinutes: 45,
    ingredients: [
      { name: 'Milk', qty: 1.5, unit: 'L' },
      { name: 'Rice', qty: 100, unit: 'g' },
      { name: 'Sugar', qty: 150, unit: 'g' },
      { name: 'Cardamom Powder', qty: 0.5, unit: 'tsp' },
      { name: 'Almonds', qty: 20, unit: 'g' },
      { name: 'Pistachios', qty: 20, unit: 'g' },
      { name: 'Raisins', qty: 20, unit: 'g' },
    ],
    steps: [
      'Rinse rice and soak for 15 minutes, then drain.',
      'Bring milk to a boil in a heavy-bottom pot.',
      'Add rice and simmer on low heat, stirring frequently to prevent sticking.',
      'Cook for 35-40 minutes until rice is soft and milk has thickened.',
      'Add sugar, cardamom, and half the nuts; cook 5 more minutes.',
      'Garnish with remaining nuts and raisins. Serve warm or chilled.',
    ],
    notes: 'Stir often — milk burns fast. For richer kheer, use full-cream milk.',
    createdAt: NOW,
  },
  {
    id: 6,
    name: 'Aloo Paratha',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 25,
    ingredients: [
      { name: 'Wheat Flour (Atta)', qty: 500, unit: 'g' },
      { name: 'Potatoes', qty: 4, unit: 'pcs' },
      { name: 'Green Chillies', qty: 2, unit: 'pcs' },
      { name: 'Coriander', qty: 1, unit: 'bunch' },
      { name: 'Cumin Seeds', qty: 1, unit: 'tsp' },
      { name: 'Red Chilli Powder', qty: 0.5, unit: 'tsp' },
      { name: 'Ghee', qty: 50, unit: 'g' },
      { name: 'Salt', qty: 1, unit: 'tsp' },
    ],
    steps: [
      'Knead a soft dough with atta, water, and a pinch of salt. Rest 15 minutes.',
      'Boil and mash potatoes. Mix with chopped chillies, coriander, cumin, chilli, and salt.',
      'Divide dough into balls. Flatten, place a spoon of filling, seal and roll gently.',
      'Cook on a hot tawa with ghee until golden brown on both sides.',
      'Serve hot with yogurt, pickle, or butter.',
    ],
    notes: 'Don\'t overfill or the paratha will tear. Dust with flour while rolling.',
    createdAt: NOW,
  },
];
